name: Build CheatEngine server for android

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build ceserver
        working-directory: Cheat Engine/ceserver/ndk-build/EXECUTABLE
        run: ndk-build NDK_PROJECT_PATH="."

      - name: Upload ceserver
        uses: actions/upload-artifact@v3.1.2

        with:
          name: android-ceserver
          path: Cheat Engine/ceserver/ndk-build/EXECUTABLE/libs/
