name: Build CheatEngine server for android

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build ceserver
        working-directory: Cheat Engine/ceserver/ndk-build
        run: |
          tree
          ndk-build APP_BUILD_SCRIPT="./EXECUTABLE/jni/Android.mk" NDK_APPLICATION_MK="./EXECUTABLE/jni/Application.mk"
          tree
